(function(root){'use strict';
const norm=s=>String(s??'').normalize('NFKC').replace(/[−–—]/g,'-').replace(/[’‘]/g,"'").trim();
const compact=s=>norm(s).replace(/\s+/g,'');
const english=s=>norm(s).toLowerCase().replace(/[,，]/g,'').replace(/[.!?。？！]+$/g,'').replace(/\s+/g,' ').trim();
// Parse arithmetic with one variable. Division is allowed only by a constant.
function polynomial(source){let s=compact(source).replace(/[×·]/g,'*').replace(/÷/g,'/').replace(/[ｘＸ]/g,'x');if(!s||s.length>180||/[^0-9.x+*/()\-]/.test(s))throw Error('式の文字を確認');let raw=s.match(/\d+(?:\.\d+)?|\.\d+|x|[+*/()\-]/g)||[];if(raw.join('')!==s)throw Error('式を確認');let t=[];raw.forEach((v,i)=>{let p=raw[i-1];if(p&&(/[\dx)]$/.test(p))&&(/^(?:\d|\.|x|\()/.test(v)))t.push('*');t.push(v)});let i=0;const add=(a,b,k=1)=>Array.from({length:Math.max(a.length,b.length)},(_,j)=>(a[j]||0)+k*(b[j]||0));const mul=(a,b)=>{if(a.length+b.length>8)throw Error('次数');let c=Array(a.length+b.length-1).fill(0);a.forEach((v,j)=>b.forEach((w,k)=>c[j+k]+=v*w));return c};function atom(){let v=t[i++];if(v==='+')return atom();if(v==='-')return atom().map(x=>-x);if(v==='('){let a=expr();if(t[i++]!==')')throw Error('括弧');return a}if(v==='x')return[0,1];if(v&&/^\d|^\./.test(v))return[Number(v)];throw Error('式')}function term(){let a=atom();while(t[i]==='*'||t[i]==='/'){let op=t[i++],b=atom();if(op==='*')a=mul(a,b);else{if(b.slice(1).some(v=>Math.abs(v)>1e-10)||Math.abs(b[0])<1e-10)throw Error('分母');a=a.map(v=>v/b[0])}}return a}function expr(){let a=term();while(t[i]==='+'||t[i]==='-'){let op=t[i++];a=add(a,term(),op==='+'?1:-1)}return a}let a=expr();if(i!==t.length||a.some(x=>!Number.isFinite(x)))throw Error('式');return a}
const polyEqual=(a,b)=>{try{a=polynomial(a);b=polynomial(b);return Array.from({length:Math.max(a.length,b.length)},(_,i)=>Math.abs((a[i]||0)-(b[i]||0))<1e-8).every(Boolean)}catch{return false}};
function check(q,input){const v=norm(input),c=compact(v);if(!c)return false;if(q.grader==='polynomial')return polyEqual(v,q.answer);if(q.grader==='equation'){const m=c.match(/^([a-zA-Z])=(.+)$/);if(!m||m[1]!==q.variable)return false;try{let a=polynomial(m[2]);return a.slice(1).every(n=>Math.abs(n)<1e-9)&&Math.abs(a[0]-q.value)<1e-8}catch{return false}}if(q.grader==='english')return [q.answer,...(q.alt||[])].some(a=>english(a)===english(v));return [q.answer,...(q.alt||[])].some(a=>compact(a)===c)}
function shuffle(a,rng=Math.random){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function stat(history,id){let h=history.filter(x=>x.skill===id&&x.source!=='held'),m=h.filter(x=>x.source==='machine'),s=h.filter(x=>x.source==='self');let recent=m.slice(-8),last=h.at(-1);return{attempts:m.length,correct:m.filter(x=>x.ok).length,selfAttempts:s.length,selfCorrect:s.filter(x=>x.ok).length,last,lastMachine:m.at(-1),recent,wrong:m.filter(x=>!x.ok).length}}
function priority(history,id,now=Date.now()){let st=stat(history,id);if(!st.last)return 5;const recent=st.recent;let rate=recent.length?recent.filter(x=>x.ok).length/recent.length:.5;let days=(now-st.last.at)/86400000;return 1+(1-rate)*5+(recent.length<3?2:0)+(days>=1?2:0)+(st.last.ok?0:3)}
root.MTCore={norm,compact,english,polynomial,polyEqual,check,shuffle,stat,priority};
})(typeof window!=='undefined'?window:globalThis);
